.\"                                      PAFY manpage
.\" (C) Copyright 2014 Zlatan Todoric <zlatan.todoric@gmail.com>,

.TH pafy 1 "April 14, 2014" "pafy manpage"
.SH NAME
pafy\- Python API for YouTube

.SH DESCRIPTION
Download videos and retrieve metadata from YouTube. This python library can
retrieve metadata such as viewcount, duration, rating, author, 
thumbnail, keywords, download video or audio at requested resolution / bitrate
/ format / filesize, command line tool (ytdl) for downloading directly from
the command line, retrieve the URL to stream the video in a player such as vlc
or mplayer, works with age-restricted videos and non-embeddable videos, small,
standalone, select highest quality stream for download or streaming, download
audio only (no video) in ogg or m4a format, download video only (no audio) in
m4v format.

.SH AUTHOR
Create by Zlatan Todoric for usage in Debian Project but can be used by others as well.
